### ISSUE TITLE
Discord 

### ISSUE THREAD

**Issue by qnnqw** [Xenia0/Makfn-Internal-Source-Code#3]
Hey What is you discord name I to buy protection and a Loader

**Comment by makfncom** [comment]
His Discord is Xenia#8888

**Comment by Xenia0** [comment]
Dude stop snitching...

**Comment by makfncom** [comment]
Wouldn't recommend paying him for protection though, he's been caught stealing code and doing malware. https://doxbin.org/upload/AryanKumarUpdatedDox, would stay away from him if I were you. He's an absolute parasite to deal with.

**Comment by Xenia0** [comment]
lmfao, yes stealing code and malware 🙏 , didnt you try to rat me like 5 times? and then you token log ppl? and then you paste?
